### ISSUE TITLE
Feature request: Option -k to pass pasword in batch

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/libstorj-c#126]
The node version take `-k`to pass the password to the app, that make it possible to use storj in batch scripts.

**Comment by braydonf** [comment]
There are three environment variables that can be used:
`STORJ_BRIDGE_USER`
`STORJ_BRIDGE_PASS`
`STORJ_MNEMONIC`

That is until there is an agent daemon that will handle remembering these, as well as auto complete. 

I don't think it's necessary to add the `-k` option, since commands are logged in bash history, and so would the password.

**Comment by BlackDuck888** [comment]
This is handy. Thank you.
